# Generated by Django 3.2.6 on 2021-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alex_urtubia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
