# Generated by Django 3.2.6 on 2021-08-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alex_urtubia', '0002_auto_20210820_2045'),
        ('Alex_urtubia', '0002_auto_20210820_2059'),
    ]

    operations = [
    ]
