# Generated by Django 3.2.6 on 2021-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tiempo', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
