# Generated by Django 3.2.3 on 2021-08-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvaro_castillo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
