# Generated by Django 3.2.3 on 2021-08-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Producto')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
            ],
        ),
    ]
