# Generated by Django 3.2.3 on 2021-08-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ariel_gonzalez', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
