# Generated by Django 3.2.6 on 2021-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariel_gonzalez', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
